# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e2e3d8"

# Title color for boxes
theme[title]="#b1d18a"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#bfcbad"

# Background color of selected item in processes box
theme[selected_bg]="#b1d18a"

# Foreground color of selected item in processes box
theme[selected_fg]="#1f3701"

# Color of inactive/disabled text
theme[inactive_fg]="#c5c8ba"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a0cfcc"

# Cpu box outline color
theme[cpu_box]="#8e9285"

# Memory/disks box outline color
theme[mem_box]="#8e9285"

# Net up/down box outline color
theme[net_box]="#8e9285"

# Processes box outline color
theme[proc_box]="#8e9285"

# Box divider line and small boxes line color
theme[div_line]="#44483d"

# Temperature graph colors
theme[temp_start]="#bfcbad"
theme[temp_mid]="#b1d18a"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#bfcbad"
theme[cpu_mid]="#b1d18a"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#bfcbad"
theme[free_mid]=""
theme[free_end]="#404a33"

# Mem/Disk cached meter
theme[cached_start]="#a0cfcc"
theme[cached_mid]=""
theme[cached_end]="#1f4e4b"

# Mem/Disk available meter
theme[available_start]="#b1d18a"
theme[available_mid]=""
theme[available_end]="#344e16"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#bfcbad"
theme[download_mid]="#b1d18a"
theme[download_end]="#a0cfcc"

# Upload graph colors
theme[upload_start]="#bfcbad"
theme[upload_mid]="#b1d18a"
theme[upload_end]="#a0cfcc"